services:
  - type: web
    name: adong-daytrade
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FUGLE_API_KEY
        sync: false
